Add release notes for 2021.1.2 Eos.
vircadia/vircadia-docs-sphinx pull request #154
Opened 2021-05-25 22:43 UTC by digisomni

2021-05-26 08:05 UTC, ctrlaltdavid requested changes

2021-05-26 08:05 UTC, ctrlaltdavid commented on docs/source/release-notes/2021-1-2-Eos.md
> +-  Update Snapshot.cpp [#1193](https://github.com/vircadia/vircadia/pull/1193)
```suggestion
-  Update snapshot image metadata to refer to Vricadia. [#1193](https://github.com/vircadia/vircadia/pull/1193)
```
This doesn't say what the update actually was.

2021-05-26 08:05 UTC, ctrlaltdavid commented on docs/source/release-notes/2021-1-2-Eos.md
> +- [**android**] fix PR autobuild for ubuntu-18.04, android with correct cmake version [#1225](https://github.com/vircadia/vircadia/pull/1225)
```suggestion
- [**android**] Fix PR autobuild for ubuntu-18.04, android with correct cmake version. [#1225](https://github.com/vircadia/vircadia/pull/1225)
```

2021-05-26 08:05 UTC, ctrlaltdavid commented on docs/source/release-notes/2021-1-2-Eos.md
> +- [**docs**] Fix missed JSDoc tag change [#1217](https://github.com/vircadia/vircadia/pull/1217)
Probably don't need `**docs** at the start of each because they're all in the `## Docs` section.

2021-05-26 08:05 UTC, ctrlaltdavid commented on docs/source/release-notes/2021-1-2-Eos.md
> +- [**docs**] Fix typo in Doxygen ReadMe [#1220](https://github.com/vircadia/vircadia/pull/1220)
Could just append the PR number to the previous item, "Add Doxygen tool for compiling C++ documentation".

2021-05-30 06:14 UTC, ctrlaltdavid requested changes

2021-05-30 06:14 UTC, ctrlaltdavid commented on docs/source/release-notes/2021-1-2-Eos.md
> +This version of Vircadia is an update to 2021.1.1. It is compatible with the 2020.1.0 Eos protocol. This version was released on May 27th, 2021.
Update date.

2021-05-30 06:14 UTC, ctrlaltdavid commented on docs/source/release-notes/2021-1-2-Eos.md
> +-  Implement VIRCADIA_MEMORY_DEBUGGING for Windows [#1171](https://github.com/vircadia/vircadia/pull/1171)
```suggestion
-  Add Doxygen tool for compiling C++ documentation. [#1212, #1220](https://github.com/vircadia/vircadia/pull/1212)
-  Include Vircadia Web app as a Git submodule. [#1202](https://github.com/vircadia/vircadia/pull/1202)
-  ReadyPlayerMe blendshapes support. [#1183](https://github.com/vircadia/vircadia/pull/1183)
-  Update to Qt 5.15.2. [#938](https://github.com/vircadia/vircadia/pull/938)
- [**osx**] Revise OSX DMGs. [#1162](https://github.com/vircadia/vircadia/pull/1162)
-  Implement VIRCADIA_MEMORY_DEBUGGING for Windows. [#1171](https://github.com/vircadia/vircadia/pull/1171)
```

2021-05-30 06:14 UTC, ctrlaltdavid commented on docs/source/release-notes/2021-1-2-Eos.md
> +-  Fix minitablet goto [#1182](https://github.com/vircadia/vircadia/pull/1182)
```suggestion
- [**linux**] Link to pthread last. [#1188](https://github.com/vircadia/vircadia/pull/1188)
-  Update snapshot image metadata to refer to Vircadia. [#1193](https://github.com/vircadia/vircadia/pull/1193)
- [**linux**] Add patch for building Qt 5.15 on gcc11. [#1218](https://github.com/vircadia/vircadia/pull/1218)
-  Fix mismatched if in CMake warning. [#1173](https://github.com/vircadia/vircadia/pull/1173)
- [**android**] Fix PR autobuild for Ubuntu-18.04, android with correct cmake version. [#1225](https://github.com/vircadia/vircadia/pull/1225)
-  Fix GitHub Actions merge-to-master MacOS build. [#1199](https://github.com/vircadia/vircadia/pull/1199)
-  Fix settings (QML) spin box stepping. [#1161](https://github.com/vircadia/vircadia/pull/1161)
- [**renderer**] Fix glTF mesh colors. [#1181](https://github.com/vircadia/vircadia/pull/1181)
-  Fix LOD manager defaults + settings not being saved correctly. [#1129](https://github.com/vircadia/vircadia/pull/1129)
-  Fix minitablet Goto. [#1182](https://github.com/vircadia/vircadia/pull/1182)
```

2021-05-30 06:14 UTC, ctrlaltdavid commented on docs/source/release-notes/2021-1-2-Eos.md
> +- Update BUILD_WIN.md with Qt Info [#1177](https://github.com/vircadia/vircadia/pull/1177)
```suggestion
- Fix missed JSDoc tag change. [#1217](https://github.com/vircadia/vircadia/pull/1217)
- Fix non-consecutive header level increases in build docs. [#1196](https://github.com/vircadia/vircadia/pull/1196)
- Update BUILD_WIN.md with Qt Info. [#1177](https://github.com/vircadia/vircadia/pull/1177)
```

2021-05-30 13:21 UTC, JulianGro approved these changes
Would be nice if you could mention issue https://github.com/vircadia/vircadia/issues/801
But even without that everything looks alright

2021-05-30 13:21 UTC, JulianGro commented on docs/source/release-notes/2021-1-2-Eos.md
> +-  Update to Qt 5.15.2. [#938](https://github.com/vircadia/vircadia/pull/938)
It might make sense to mention that this fixes a pretty bad bug on Linux AMD: https://github.com/vircadia/vircadia/issues/801

2021-05-30 20:05 UTC, ctrlaltdavid approved these changes
OK, though see Julian's comment.

2021-05-31 00:05 UTC, merged