Add video module
vircadia/vircadia-docs-sphinx pull request #72
Opened 2020-07-31 17:48 UTC by JulianGro

This PR adds a video module (thanks to Madders for that)

Specifically it changes:
- update readme for new dependency and and instructions
- convert all gif animated files to webm (vp9) and mp4 (h264)
  - change all animated gif occurences in documentation to the new video module
  - remove now unused animated gif files

TODO: convert some docs from markdown to RST to allow for usage of new video module

2020-09-14 01:32 UTC, ctrlaltdavid requested changes
Videos seem to need CSS styling to add whitespace under them. For example, the videos in the Create > Entities > Add a Material Entity page have no whitespace at their bottom before their following text starts. It's particularly noticeable that the heading "Use the materialData 
field" has no whitespace above it.

Additionally, videos should be centred horizontally, the same as images. For example, the videos on the Create > Entities > Change How Entities Look page are left-aligned whereas images are centred.

2020-09-14 01:32 UTC, ctrlaltdavid commented on README.md
> +When adding videos to the documentation, it is important to use h264 *and* vp9 to ensure they can be played it all major internet browsers.
```suggestion
When adding videos to the documentation, it is important to use h264 *and* vp9 to ensure that they can be played it all major web browsers.
```

2020-09-14 03:31 UTC, ctrlaltdavid requested changes

2020-09-14 03:31 UTC, ctrlaltdavid commented on README.md
> +    ```
```suggestion

    ```
```
Blank line needed in order for command text to be displayed in its own container.

2020-09-14 03:31 UTC, ctrlaltdavid commented on README.md
> +    ```
```suggestion

    ```
```

2020-09-14 03:35 UTC, ctrlaltdavid approved these changes

2020-09-20 05:54 UTC, JulianGro commented
Closes #74

2020-10-06 17:43 UTC, JulianGro commented
@kasenvr apparently I borked the history by rebasing on master. 18cccaa is the latest commit and has already been approved by @ctrlaltdavid

2020-10-06 18:43 UTC, ctrlaltdavid approved these changes

2020-12-17 10:54 UTC, digisomni commented on docs/source/conf.py
> +extensions = ['sphinxcontrib.video']
```suggestion

# -- Additional Extensions ---------------------------------------------------
extensions = ['recommonmark', 'sphinxcontrib.video']

```

2020-12-17 10:54 UTC, digisomni commented on docs/source/conf.py
> +extensions = ['sphinxcontrib.video']
This will fix markdown parsing.

2020-12-17 10:57 UTC, digisomni commented
After the merge conflict is solved and suggestion is applied, this can be merged with follow-up review on PR #105 to apply anything left.

2020-12-20 21:37 UTC, digisomni approved these changes
All good, so the only follow-up is PR 105. No rush on that though since the MD parsing was fixed in this PR.

2020-12-20 21:37 UTC, merged